version: '3.8'

services:
  trading-bot:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: python main.py
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M