# Core settings
core:
  name: "Omnia Strategy"
  version: "1.0.0"
  lookback_window: 252
  update_frequency: "daily"

# Market regime settings
regime:
  crisis_vol_threshold: 30
  crisis_corr_threshold: 0.7
  risk_off_threshold: -0.5
  risk_on_threshold: 0.5
  trend_threshold: 0.3
  euphoria_trend_threshold: 0.7

# Weight settings
weights:
  macro:
    geopolitical: 0.30
    economic: 0.30
    monetary: 0.20
    sentiment: 0.20
  
  algorithmic:
    trend: 0.30
    momentum: 0.25
    mean_reversion: 0.25
    ml_predictor: 0.20

# Risk management
risk:
  max_position_size: 0.1
  max_portfolio_heat: 0.25
  vol_target: 0.15
  max_drawdown: 0.20
  correlation_threshold: 0.7

# Data settings
data:
  primary_timeframe: "1D"
  secondary_timeframes: ["1H", "4H", "1W"]
  min_history_required: 252
