# Core settings
core:
  name: "Omnia Strategy"
  version: "1.0.0"
  lookback_window: 252  # Number of days for the lookback window
  update_frequency: "daily"  # Update frequency: daily, weekly, etc.

# Strategy settings
strategy:
  name: "ExampleStrategy"
  timeframe: "1D"
  risk_per_trade: 0.01

# Market regime settings
regime:
  crisis_vol_threshold: 30  # Volatility threshold for crisis regime
  crisis_corr_threshold: 0.7  # Correlation threshold for crisis regime
  risk_off_threshold: -0.5  # Threshold for risk-off regime
  risk_on_threshold: 0.5  # Threshold for risk-on regime
  trend_threshold: 0.3  # Threshold for trend detection
  euphoria_trend_threshold: 0.7  # Threshold for euphoria trend

# Weight settings
weights:
  macro:
    geopolitical: 0.30
    economic: 0.30
    monetary: 0.20
    sentiment: 0.20
  
  algorithmic:
    trend: 0.30  # Weight for trend strategy
    momentum: 0.25  # Weight for momentum strategy
    mean_reversion: 0.25  # Weight for mean reversion strategy
    ml_predictor: 0.20  # Weight for machine learning predictor

# Risk management
risk:
  max_position_size: 0.1  # Maximum size of any single position (as a fraction of total portfolio)
  max_portfolio_heat: 0.25  # Maximum portfolio heat (risk exposure)
  vol_target: 0.15  # Target portfolio volatility
  max_drawdown: 0.20  # Maximum allowable drawdown
  correlation_threshold: 0.7  # Maximum allowable correlation between positions

# Data settings
data:
  primary_timeframe: "1D"  # Primary timeframe for data analysis
  secondary_timeframes: ["1H", "4H", "1W"]  # Secondary timeframes for additional context
  min_history_required: 252  # Minimum historical data required (in days)